# Generated by Django 5.2.8 on 2025-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsetting_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.CharField(choices=[('প্রশ্নপত্র প্রণয়ন', 'প্রশ্নপত্র প্রণয়ন'), ('উত্তরপত্র মূল্যায়ন', 'উত্তরপত্র মূল্যায়ন'), ('ভাইভা', 'ভাইভা'), ('প্র্যাকটিক্যাল', 'প্র্যাকটিক্যাল'), ('ক্লাস টেস্ট', 'ক্লাস টেস্ট'), ('টিউটোরিয়াল', 'টিউটোরিয়াল')], max_length=50, verbose_name='কাজের ধরণ'),
        ),
    ]
