# Generated by Django 5.2.8 on 2026-01-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bill_account_number_bill_bank_branch_bill_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='কাজের ধরণ')),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'কাজের ধরণ',
                'verbose_name_plural': 'কাজের ধরণসমূহ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='পরিমাণ'),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='একক'),
        ),
        migrations.AlterField(
            model_name='task',
            name='benefit',
            field=models.CharField(max_length=100, verbose_name='উপকাজ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.CharField(max_length=100, verbose_name='কাজের ধরণ'),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='উপকাজের নাম')),
                ('calculation_type', models.CharField(choices=[('fixed', 'নির্দিষ্ট পরিমাণ'), ('per_paper', 'প্রতি কপি'), ('per_question', 'প্রতি প্রশ্ন'), ('per_hour', 'প্রতি ঘণ্টা'), ('per_student', 'প্রতি শিক্ষার্থী'), ('per_semester', 'প্রতি সেমিস্টার')], default='fixed', max_length=20, verbose_name='গণনা পদ্ধতি')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ভিত্তি পরিমাণ')),
                ('unit_label', models.CharField(blank=True, max_length=50, verbose_name='একক লেবেল (যেমন: কপি, প্রশ্ন)')),
                ('min_unit', models.PositiveIntegerField(default=1, verbose_name='ন্যূনতম একক')),
                ('max_unit', models.PositiveIntegerField(default=100, verbose_name='সর্বোচ্চ একক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.worktype', verbose_name='কাজের ধরণ')),
            ],
            options={
                'verbose_name': 'উপকাজ',
                'verbose_name_plural': 'উপকাজসমূহ',
                'ordering': ['work_type', 'order', 'name'],
            },
        ),
    ]
