# Generated by Django 5.2.8 on 2025-11-09 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='ছবি')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True, verbose_name='বিল নম্বর')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='ভাউচার নম্বর')),
                ('semester', models.CharField(choices=[('১ম সেমিস্টার', '১ম সেমিস্টার'), ('২য় সেমিস্টার', '২য় সেমিস্টার'), ('৩য় সেমিস্টার', '৩য় সেমিস্টার'), ('৪র্থ সেমিস্টার', '৪র্থ সেমিস্টার'), ('৫ম সেমিস্টার', '৫ম সেমিস্টার'), ('৬ষ্ঠ সেমিস্টার', '৬ষ্ঠ সেমিস্টার'), ('৭ম সেমিস্টার', '৭ম সেমিস্টার'), ('৮ম সেমিস্টার', '৮ম সেমিস্টার')], max_length=20, verbose_name='সেমিস্টার')),
                ('department', models.CharField(default='কম্পিউটার বিজ্ঞান এবং প্রকৌশল', max_length=100, verbose_name='বিভাগ')),
                ('bangla_date', models.CharField(max_length=50, verbose_name='বাংলা তারিখ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='মোট টাকা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('চেয়ারম্যান', 'চেয়ারম্যান'), ('অ্যাসিস্ট্যান্ট প্রফেসর', 'অ্যাসিস্ট্যান্ট প্রফেসর'), ('লেকচারার', 'লেকচারার'), ('অফিস সহকারী', 'অফিস সহকারী')], max_length=50, verbose_name='পদবী')),
                ('profile_picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/', verbose_name='প্রোফাইল ছবি')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('প্রশ্নপত্র প্রণয়ন', 'প্রশ্নপত্র প্রণয়ন'), ('প্রশ্নপত্র মূল্যায়ন', 'প্রশ্নপত্র মূল্যায়ন'), ('ভাইভা', 'ভাইভা'), ('প্র্যাকটিক্যাল', 'প্র্যাকটিক্যাল'), ('ক্লাস টেস্ট', 'ক্লাস টেস্ট'), ('টিউটোরিয়াল', 'টিউটোরিয়াল')], max_length=50, verbose_name='কাজের ধরণ')),
                ('benefit', models.CharField(max_length=50, verbose_name='উপকাজ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.bill')),
            ],
        ),
    ]
