# Generated by Django 5.2.8 on 2025-11-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at'], 'verbose_name': 'বিল', 'verbose_name_plural': 'বিলগুলি'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'কাজ', 'verbose_name_plural': 'কাজগুলি'},
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের সময়'),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী'),
        ),
        migrations.AddField(
            model_name='bill',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='মন্তব্য'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='যোগদানের তারিখ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ফোন নম্বর'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ক্রম'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
