# Generated by Django 5.2.8 on 2025-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='একাউন্ট নাম্বার'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='শাখা'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('জনতা ব্যাংক', 'জনতা ব্যাংক'), ('ডাচ বাংলা ব্যাংক', 'ডাচ বাংলা ব্যাংক'), ('সোনালী ব্যাংক', 'সোনালী ব্যাংক'), ('ইসলামী ব্যাংক', 'ইসলামী ব্যাংক')], max_length=50, null=True, verbose_name='ব্যাংকের নাম'),
        ),
        migrations.AddField(
            model_name='bill',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='রাউটিং নাম্বার'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.CharField(choices=[('প্রশ্নপত্র প্রণয়ন', 'প্রশ্নপত্র প্রণয়ন'), ('উত্তরপত্র মূল্যায়ন', 'উত্তরপত্র মূল্যায়ন'), ('ভাইভা', 'ভাইভা'), ('প্র্যাকটিক্যাল', 'প্র্যাকটিক্যাল'), ('ক্লাস টেস্ট', 'ক্লাস টেস্ট'), ('প্রশ্নপত্র সমীক্ষণ', 'প্রশ্নপত্র সমীক্ষণ'), ('পরীক্ষা কমিটির সম্মানী', 'পরীক্ষা কমিটির সম্মানী'), ('প্রশ্নপত্র প্রিন্টিং ও প্যাকেজিং', 'প্রশ্নপত্র প্রিন্টিং ও প্যাকেজিং'), ('প্রশ্নপত্র কম্পোজ', 'প্রশ্নপত্র কম্পোজ')], max_length=50, verbose_name='কাজের ধরণ'),
        ),
    ]
