# Generated by Django 5.2.8 on 2026-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_worktype_task_quantity_task_unit_alter_task_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='needs_benefit',
            field=models.BooleanField(default=True, verbose_name='উপকাজ প্রয়োজন?'),
        ),
    ]
