# Generated by Django 5.2.8 on 2026-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_worktype_needs_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ডিফল্ট পরিমাণ (যদি উপকাজের দরকার না থাকে)'),
        ),
    ]
