# Generated by Django 5.2.8 on 2026-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_worktype_default_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'নির্দিষ্ট পরিমাণ'), ('per_piece', 'কতটি'), ('per_paper', 'প্রতি কপি'), ('per_question', 'প্রতি প্রশ্ন'), ('per_hour', 'প্রতি ঘণ্টা'), ('per_student', 'প্রতি শিক্ষার্থী'), ('per_semester', 'প্রতি সেমিস্টার')], default='fixed', max_length=20, verbose_name='গণনা পদ্ধতি'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='unit_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='একক লেবেল (যেমন: কতটি, কপি, প্রশ্ন)'),
        ),
    ]
