# Generated by Django 5.2.8 on 2026-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bill_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='degree_type',
            field=models.CharField(choices=[('honors', 'অনার্স'), ('masters', 'মাস্টার্স')], default='honors', max_length=10, verbose_name='ডিগ্রির ধরণ'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='degree_type',
            field=models.CharField(choices=[('both', 'উভয়'), ('honors', 'অনার্স'), ('masters', 'মাস্টার্স')], default='both', max_length=10, verbose_name='ডিগ্রির ধরণ'),
        ),
    ]
