# Generated by Django 5.2.8 on 2026-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_worktype_name_alter_benefit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='পাঠানোর সময়'),
        ),
    ]
