# Generated by Django 5.2.8 on 2026-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_signature_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_hidden_from_chairman',
            field=models.BooleanField(default=False, verbose_name='চেয়ারম্যানের কাছে লুকানো'),
        ),
    ]
