# Generated by Django 5.2.8 on 2026-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_signature_chairman1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='chairman_signature_added',
            field=models.BooleanField(default=False, verbose_name='চেয়ারম্যানের স্বাক্ষর যুক্ত হয়েছে'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_signature_added',
            field=models.BooleanField(default=False, verbose_name='ব্যবহারকারীর স্বাক্ষর যুক্ত হয়েছে'),
        ),
    ]
