# Generated by Django 5.2.8 on 2026-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bill_chairman_signature_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='মন্তব্য'),
        ),
    ]
