# Generated by Django 6.0.2 on 2026-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sent_to_controller_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='কন্ট্রোলে পাঠানোর সময়'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('sent_to_controller', 'Sent to Controller')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
    ]
