# Generated by Django 6.0.2 on 2026-05-15 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bill_sent_to_controller_at_alter_bill_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='controller_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='কন্ট্রোলার অনুমোদনের সময়'),
        ),
        migrations.AddField(
            model_name='bill',
            name='controller_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='কন্ট্রোলার অনুমোদনকারী'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('sent_to_controller', 'Sent to Controller'), ('approved_by_controller', 'Approved by Controller'), ('rejected_by_controller', 'Rejected by Controller')], default='pending', max_length=30, verbose_name='স্ট্যাটাস'),
        ),
    ]
