# Generated by Django 6.0.2 on 2026-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bill_controller_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='বর্ণনা'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='শিরোনাম'),
        ),
    ]
