# Generated by Django 6.0.2 on 2026-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_sliderimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='chairman_signature_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='চেয়ারম্যানের স্বাক্ষর URL'),
        ),
        migrations.AddField(
            model_name='bill',
            name='signed_by_chairman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='স্বাক্ষরকারী চেয়ারম্যান'),
        ),
        migrations.AddField(
            model_name='bill',
            name='signed_by_chairman_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='চেয়ারম্যানের বর্ষ'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user_signature_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ব্যবহারকারীর স্বাক্ষর URL'),
        ),
    ]
