# Generated by Django 6.0.2 on 2026-05-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_bill_chairman_signature_url_bill_signed_by_chairman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='chairman_signature_url',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='signed_by_chairman',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='signed_by_chairman_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user_signature_url',
        ),
    ]
