# Generated by Django 6.0.7 on 2026-07-18 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_bill_chairman_signature_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='resend_count',
            field=models.PositiveIntegerField(default=0, verbose_name='পুনঃপ্রেরণ সংখ্যা'),
        ),
        migrations.AddField(
            model_name='bill',
            name='returned_to_chairman_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='চেয়ারম্যানে ফেরত পাঠানোর সময়'),
        ),
        migrations.AddField(
            model_name='bill',
            name='returned_to_chairman_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_returned_bills', to=settings.AUTH_USER_MODEL, verbose_name='ফেরতকারী কন্ট্রোলার'),
        ),
        migrations.AddField(
            model_name='bill',
            name='returned_to_user_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ব্যবহারকারীর কাছে ফেরত পাঠানোর সময়'),
        ),
        migrations.AddField(
            model_name='bill',
            name='returned_to_user_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_returned_bills', to=settings.AUTH_USER_MODEL, verbose_name='ফেরতকারী চেয়ারম্যান'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'নির্দিষ্ট পরিমাণ'), ('per_piece', 'কতটি'), ('per_paper', 'প্রতি কপি'), ('per_question', 'প্রতি প্রশ্ন'), ('per_hour', 'প্রতি ঘণ্টা'), ('per_student', 'প্রতি শিক্ষার্থী'), ('per_semester', 'প্রতি সেমিস্টার'), ('per_person', 'জনপ্রতি'), ('per_day', 'প্রতি দিন')], default='fixed', max_length=20, verbose_name='গণনা পদ্ধতি'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('sent_to_controller', 'Sent to Controller'), ('approved_by_controller', 'Approved by Controller'), ('rejected_by_controller', 'Rejected by Controller'), ('controller_returned', 'Returned to Chairman by Controller'), ('returned_to_user', 'Returned to User')], default='pending', max_length=30, verbose_name='স্ট্যাটাস'),
        ),
    ]
