# Generated by Django 6.0.2 on 2026-07-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bill_resend_count_bill_returned_to_chairman_at_and_more'),
        ('core', '0023_profile_updated_at'),
    ]

    operations = [
    ]
