# Generated by Django 6.0.2 on 2026-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_masters_and_read_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='controller_bill_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='কন্ট্রোলার বিল নম্বর'),
        ),
    ]
