# Generated by Django 6.0.2 on 2026-07-30 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bill_controller_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='যেমন: ১০ লিখলে মোট টাকার ১০% কর কাটা হবে।', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='করের হার (%)')),
                ('label', models.CharField(blank=True, help_text='ঐচ্ছিক, যেমন: আয়কর', max_length=100, verbose_name='নাম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ পরিবর্তন')),
            ],
            options={
                'verbose_name': 'কর (ট্যাক্স) সেটিং',
                'verbose_name_plural': 'কর (ট্যাক্স) সেটিং',
                'ordering': ['-updated_at'],
            },
        ),
    ]
