# Generated by Django 5.2.8 on 2026-02-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bill_degree_type_worktype_degree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='কাজের ধরণ'),
        ),
        migrations.AlterUniqueTogether(
            name='benefit',
            unique_together={('work_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together={('name', 'degree_type')},
        ),
    ]
