# Generated by Django 5.2.8 on 2026-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_benefit_calculation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='semester',
            field=models.CharField(choices=[('১ম সেমিস্টার', '১ম সেমিস্টার'), ('২য় সেমিস্টার', '২য় সেমিস্টার'), ('৩য় সেমিস্টার', '৩য় সেমিস্টার'), ('৪র্থ সেমিস্টার', '৪র্থ সেমিস্টার'), ('৫ম সেমিস্টার', '৫ম সেমিস্টার'), ('৬ষ্ঠ সেমিস্টার', '৬ষ্ঠ সেমিস্টার'), ('৭ম সেমিস্টার', '৭ম সেমিস্টার'), ('৮ম সেমিস্টার', '৮ম সেমিস্টার'), ('মাস্টার্স', 'মাস্টার্স')], max_length=20, verbose_name='সেমিস্টার'),
        ),
    ]
