# Generated by Django 5.2.8 on 2026-03-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bill_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='স্বাক্ষর'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('চেয়ারম্যান', 'চেয়ারম্যান'), ('কন্ট্রোলার', 'কন্ট্রোলার'), ('অ্যাসিস্ট্যান্ট প্রফেসর', 'অ্যাসিস্ট্যান্ট প্রফেসর'), ('লেকচারার', 'লেকচারার'), ('অফিস সহকারী', 'অফিস সহকারী')], max_length=50, verbose_name='পদবী'),
        ),
    ]
