# Generated by Django 5.2.8 on 2026-03-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bill_is_hidden_from_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature_chairman1',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/chairman1/', verbose_name='চেয়ারম্যান ১ স্বাক্ষর'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_chairman2',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/chairman2/', verbose_name='চেয়ারম্যান ২ স্বাক্ষর'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_chairman3',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/chairman3/', verbose_name='চেয়ারম্যান ৩ স্বাক্ষর'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_chairman4',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/chairman4/', verbose_name='চেয়ারম্যান ৪ স্বাক্ষর'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_general',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/general/', verbose_name='সাধারণ স্বাক্ষর'),
        ),
    ]
